@FashionStoreWebApi_HostAddress = https://localhost:7012

GET {{FashionStoreWebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{FashionStoreWebApi_HostAddress}}/api/roles
Authorization: Bearer CfDJ8O5UgSBkQxZLrbXl6BSbfNGcTGTtdun1gvM4HzzLuKABlVf8-Mhw1Na4t4UK9XSGjL1tMdkHMGlnJ4-zsK2bgsRvk5Ico7ux3y4Ef85fII_zpPWH_0wjaqqXSVlG--MXbNKH7oRl_V_YLwfU2tcq6VNNs3AA6mNcnMkwtdIQoJ2yivr4UyhVMfn2oMfc6asX2VR2D5Vxf39tXw-2JA9GSYStGxpTMBzlF5Zep1Jjf0K6lGJTNkRBbJ4oBPbJp3DbOLipwirnEb-WoyVgTNkBcwjmBew6qhCQ2Kf_M9N9JC8ebe7KOq5mjTVRD6tWqdXvE_qLUXqtTVJq1mfqSJ2aTURj01mmEcJFNucgk-JkwW7UM0vF2SRLoMiey-Zt5mAzOzVXPn-LOxYmuxEoSFU1wMXruSz2e7zNl8iKYD-7IPBmhDj9IaNrHU02ILDwuw4We6G0Fqng7t42H3zSJ-NzJ1oZgVhhe4pQS0rCFQC7GOwC2ZRVa8CybHz8CmEjBlH4oj4oBzaHfPiEq8EuFBU5KfP3BX8dhE6rlniDHc2bzLUqFr473HjfT2g6n52erdlC79lhnlQUAYHcs59Oud41ZY73kYDlcBElQMUV7kVM6suhEVbfGdBKHMRCTVb91u-pH89B7cmNs9SBO180amU6rRtiZCxs5ETwIMkGcj3biNPs4Smo1bcbgVdpZqDzim4xtURSPm7F0DLytoSQA_7STcGQg7iLjAUS89df-_daGi5ooUQBK0P2mSa0HxGxaFmRRcUPkSUbVe2VghOrwccDM5WHFwNFmRwCpuJBnxGhupcP
###
